### ISSUE TITLE
Cannot launch debug session on MacOS

### ISSUE THREAD

**Issue by fantoine** [Kode/KodeStudio#13]
- VSCode Version: 16.8.0
- OS Version: OSX 10.11.6

Steps to Reproduce:
1. Create a simple project from Empty repository
2. Run debug session
3. You get an error 'Error: Cannot find module 'web-frame''

```
Error: Cannot find module 'web-frame'
    at Module._resolveFilename (module.js:440:15)
    at Function.Module._resolveFilename (/Applications/Kode Studio.app/Contents/Resources/app/extensions/chrome-debug/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Function.kha_SystemImpl.init (./test-map/build/debug-html5/kha.js:3082:2)
    at Function.kha_System.init (./test-map/build/debug-html5/kha.js:2945:17)
    at Function.Main.main (./test-map/build/debug-html5/kha.js:218:13)
    at ./test-map/build/debug-html5/kha.js:19018:6
    at ./test-map/build/debug-html5/kha.js:19019:3
```

**Comment by RobDangerous** [comment]
Please update your copy of Kha (sorry, Electron's api changed a little, fixed in the two latest commits to Kha).
