### ISSUE TITLE
Debugger crash on GL error in v16.11

### ISSUE THREAD

**Issue by memilian** [Kode/KodeStudio#29]
The new 16.11.x versions crash the debugger when there is a gl error.
I have a project that produce the following error in Kode 16.8 :
```
[.Offscreen-For-WebGL-0x3a904b7b5500]GL ERROR :GL_INVALID_OPERATION : glDrawElements: attempt to access out of range vertices in attribute 0
```
When I run the project in Kode 16.11.x, the debugger adapter process crash with the following error :
```java
******** Unhandled error in debug adapter: TypeError: Cannot read property '0' of undefined
    at resolveParams (/home/memilian/bin/KodeStudio/resources/app/extensions/chrome-debug/node_modules/vscode-chrome-debug-core/out/src/chrome/consoleHelper.js:51:27)
    at Object.formatConsoleMessage (/home/memilian/bin/KodeStudio/resources/app/extensions/chrome-debug/node_modules/vscode-chrome-debug-core/out/src/chrome/consoleHelper.js:17:26)
    at ChromeDebugAdapter.onConsoleAPICalled (/home/memilian/bin/KodeStudio/resources/app/extensions/chrome-debug/node_modules/vscode-chrome-debug-core/out/src/chrome/chromeDebugAdapter.js:353:50)
    at ChromeDebugAdapter.onMessageAdded (/home/memilian/bin/KodeStudio/resources/app/extensions/chrome-debug/node_modules/vscode-chrome-debug-core/out/src/chrome/chromeDebugAdapter.js:371:18)
    at Client.chrome.Console.onMessageAdded.params (/home/memilian/bin/KodeStudio/resources/app/extensions/chrome-debug/node_modules/vscode-chrome-debug-core/out/src/chrome/chromeDebugAdapter.js:143:59)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:188:7)
    at Client.processMessage (/home/memilian/bin/KodeStudio/resources/app/extensions/chrome-debug/node_modules/noice-json-rpc/lib/noice-json-rpc.js:64:18)
    at LoggingSocket.Client.socket.on.message (/home/memilian/bin/KodeStudio/resources/app/extensions/chrome-debug/node_modules/noice-json-rpc/lib/noice-json-rpc.js:28:46)
    at emitTwo (events.js:111:20)
```

To reproduce : 
```haxe
function render(framebuffer: Framebuffer): Void {
	framebuffer.g4.begin();
	framebuffer.g4.drawIndexedVertices();
	framebuffer.g4.end();
}
```

I'm running kode on linux-x64

**Comment by RobDangerous** [comment]
Uh, looks like an Electron bug, happens on Windows and macOS, too. Very ugly but will probably have to wait for vscode 1.8.

**Comment by RobDangerous** [comment]
Oh, this is fixed btw.
