### ISSUE TITLE
KodeStudio with GIT Kha wont Launch Krom on windows

### ISSUE THREAD

**Issue by hoseyjoe** [Kode/KodeStudio#53]
Using kha that come with kode studio  krom launches project.  If I change khaPath to git version I receive
`Invalid JSON from target: (Unexpected token 
 in JSON at position 149): {"method":"Log.entryAdded","params":{"entry":{"source":"javascript","level":"log","text":"Trace: TypeError: Krom.setPenDownCallback is not a function
    at Function.kha_SystemImpl.init (krom.js:4338:7)
    at Function.kha_System.init (krom.js:4075:17)
    at Function.Main.main (krom.js:157:13)
    at krom.js:20111:6","timestamp":0}}}
Error handling message from target: Unexpected token 
 in JSON at position 149`

Sample project
[BunnyMark.zip](https://github.com/Kode/KodeStudio/files/1884870/BunnyMark.zip)

Any idea when Studio can launch Krom with newest Kha?

**Comment by hoseyjoe** [comment]
You have to set kha path  & krom path in preferences
